### ISSUE TITLE
Document other modules

### ISSUE THREAD

**Issue by robrwo** [benkasminbullock/html-valid#13]
You may want to update your CPAN modules section to mention the following:
- HTML::Tidy5
- HTML::T5
- Alien::TidyHTML5

**Comment by benkasminbullock** [comment]
Your own module doesn't mention any of these.

https://metacpan.org/pod/Alien::TidyHTML5#SEE-ALSO

Anyway this is all done here: edc799891703f1c5c65f2592d9717befa1eba842
