### ISSUE TITLE
Missing prereq specification (JSON::Parse)

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/html-valid#4]
Compilation fails if JSON::Parse is not installed:

```
Can't locate JSON/Parse.pm in @INC (you may need to install the JSON::Parse module) (@INC contains: ....) at /tmpfs/.cpan-build/2015120121/HTML-Valid-0.01-IL41dl/blib/lib/HTML/Valid.pm line 11.
BEGIN failed--compilation aborted at /tmpfs/.cpan-build/2015120121/HTML-Valid-0.01-IL41dl/blib/lib/HTML/Valid.pm line 11.
Compilation failed in require at t/alt-text.t line 12.
BEGIN failed--compilation aborted at t/alt-text.t line 12.
```

**Comment by benkasminbullock** [comment]
Thanks for the report. I forgot to add the dependence in Makefile.PL. I'll release version 0.02 to CPAN in a few more hours which will fix this problem.

**Comment by benkasminbullock** [comment]
This should be OK in the latest version on CPAN, please let me know if you're not happy about this or if you find any other problems.

https://metacpan.org/release/BKB/HTML-Valid-0.02

Thanks again for the report, I really appreciate your making this effort.
