### ISSUE TITLE
Broken link in the pod

### ISSUE THREAD

**Issue by manwar** [benkasminbullock/html-valid#8]
Hi ,

I came across the broken link for "Adaptive Technology Resource Centre at the University of Toronto" in the pod document.

http://www.aprompt.ca/Tidy/accessibilitychecks.html

I would have preferred a PR but found it really hard to locate the source. 

Best Regards,
Mohammad S Anwar

**Comment by benkasminbullock** [comment]
The documentation of the options is taken directly from the source code of the parent project:

https://github.com/htacg/tidy-html5/blob/4a3f5ecf0736849e2d0c87ba42583a13b4124638/src/localize.c#L28

They've fixed that broken link in the original:

https://github.com/htacg/tidy-html5/blob/master/src/localize.c#L29

but I am sticking with the 5.0.0 version until a new release is made, for the sake of stability. Please expect this to be fixed soon. I'll leave this issue open until then.

**Comment by benkasminbullock** [comment]
This is now fixed in the most recent update:

https://metacpan.org/pod/release/BKB/HTML-Valid-0.03_01/lib/HTML/Valid.pod

Thank you for the report.
